### ISSUE TITLE
Best way to pass member function to emplace() ?

### ISSUE THREAD

**Issue by leonsal** [cpp-taskflow/cpp-taskflow#111]
Hi

What is the best way to pass a member function to "Taskflow::emplace()" ?
I tried using the same syntax accepted by `std::invoke()` but the compilation
aborted with a failed static assert:
`static_assert(dependent_false_v<C>, "invalid task work type");`
But using `std::bind()` and a lambda works.

Regards.

```
struct Node {
   void run() {
      std::cout << "Node::run()\n";
   }
};

int main() {

   tf::Taskflow taskflow;
   Node n{};
   std::invoke(&Node::run, &n);                 // Compiles OK and calls Node::run
   auto t1 = taskflow.emplace(&Node::run, &n);  // Compilation aborts !
   auto t2 = taskflow.emplace(std::bind(&Node::run, &n)) // Works
   auto t3 = taskflow.emplace([&n](){n.run();}); // Works
}

```

**Comment by tsung-wei-huang** [comment]
The underlying type of task to store a callable is `std::function`. In your case, the best way is:

```
auto t = taskflow.emplace([n=Node{}](){n.run();});
```

**Comment by leonsal** [comment]
OK. Thanks.
