### ISSUE TITLE
Task::is_placeholder()?

### ISSUE THREAD

**Issue by freehour** [cpp-taskflow/cpp-taskflow#115]
Could we have a function in Task to check whether it has some work assigned or is a placehoder?
There is Task::empty() but this only checks for a Node.
I was a bit confused that the documentation for FlowBuilder::placeholder says "creates an empty task" but Task::empty() returns false.

**Comment by clin99** [comment]
Hi @freehour , thanks for the suggestion!  We will add this to the library and update the documentation.

**Comment by freehour** [comment]
Great, thanks.

**Comment by tsung-wei-huang** [comment]
@freehour  I have modified the docs and added `has_work` to `tf::Task` to reflect your suggestion in the master branch. Thanks.
