### ISSUE TITLE
FAQ / Scheduling algorithms

### ISSUE THREAD

**Issue by robinchrist** [cpp-taskflow/cpp-taskflow#117]
Hi,

I've noticed that in the current version of TaskFlow only the WorkStealing algorithm is left...
However there's still an answer in the FAQ telling the opposite
```
Q7: How does Cpp-Taskflow schedule tasks?
Cpp-Taskflow has implemented different scheduler modules (centralized queue, proactive shceduler, speculative strategy, and work stealing). The default scheduler implements the famous work stealing algorithm that has shown to behave efficiently in most multicore architectures. You can find the source code at taskflow/core/executor.hpp
```

Are there any plans to add support for the "old" algorithms in the future?

Additionally, this in the README.md is outdated believe

Touching a taskflow or **an executor** from multiple threads is not safe

**Comment by tsung-wei-huang** [comment]
@robinchrist Thanks for your inputs. Fixed these problems.
