### ISSUE TITLE
Provide cpp-taskflow.pc configuration

### ISSUE THREAD

**Issue by xbreak** [cpp-taskflow/cpp-taskflow#122]
**Please describe your feature request.**
It would be nice if cpp-taskflow could provide a pkg-config file to make discovery and consumption of this project easier in non-cmake build systems such as autotools, make, waf, meson, build2 et.c.

**Comment by clin99** [comment]
Hi @xbreak , thanks for the suggestion!  We will survey those build systems and add the configuration file to support them in the future. Below is a simple `cpp-taskflow-2.2.0.pc` file you can modify for your use:

```bash
prefix=
includedir=cpp-taskflow

Name: Cpp-Taskflow 
Description: A Modern C++ Parallel Task Programming Library
Version: 2.2.0
Requires:
Conflicts:
Libs: -lpthread
Cflags: -std=c++17 -I${includedir}
```
