### ISSUE TITLE
Are tasks bound to threads, or can they run on any thread in the pool?

### ISSUE THREAD

**Issue by damienhocking** [cpp-taskflow/cpp-taskflow#13]

**Comment by clin99** [comment]
Task is not bound to any specific thread. A task can be executed by any thread in the pool.

**Comment by twhuang-uiuc** [comment]
@clin99 is correct. Each taskflow has a private threadpool to execute its associated tasks.

**Comment by damienhocking** [comment]
Great, thanks.  This is the cleanest task API I've ever seen.  We're going to try this out.

**Comment by twhuang-uiuc** [comment]
Thank you @damienhocking ! Please let us know if anything we can help or contribute.
