### ISSUE TITLE
Is taskflow capable of catching exception from its excuting taskflows?

### ISSUE THREAD

**Issue by zxbzswxr** [cpp-taskflow/cpp-taskflow#131]
Thank you.
there are some questions and I push it straightforward.
does try...catch  work for taskflow?
If I run a taskflow in a try catch block and throw some exceptions(not only one) in subtasks . Can taskflow library deal with it and if so, how?

**Comment by tsung-wei-huang** [comment]
Hi @zxbzswxr we didn't expand effort on exception handling. Users are responsible to hand exception on each task, like:

```cpp
taskflow.emplace([](){
  try {
     // do something here
  } catch (...) {
  }
});
```

**Comment by zxbzswxr** [comment]
@tsung-wei-huang  thanks for your reply.
