### ISSUE TITLE
Compilation error MSVC 16.4.1

### ISSUE THREAD

**Issue by corporateshark** [cpp-taskflow/cpp-taskflow#133]
Microsoft Visual Studio Community 2019
Version 16.4.1
C++20 enabled
```
cpptaskflow\taskflow\core/executor.hpp(864,41): error C3538: in a declarator-list 'std::scoped_lock' must always deduce to the same type
cpptaskflow\taskflow\core/executor.hpp(864,41): message : could be 'std::scoped_lock<>'
cpptaskflow\taskflow\core/executor.hpp(864,41): message : or       'std::scoped_lock<std::mutex>'
```

P.S. Works fine with the previous version of MSVC.

**Comment by tsung-wei-huang** [comment]
@corporateshark I think this is an issue of MSVC compiler. Template deduction is a C++17 standard though.

**Comment by corporateshark** [comment]
@tsung-wei-huang Sure thing. A have a workaround for this: https://github.com/cpp-taskflow/cpp-taskflow/pull/125/commits/cf810d2b88c4438838c5d47097472dd8c714d631
