### ISSUE TITLE
Continuous processing of input queue

### ISSUE THREAD

**Issue by dcnieho** [cpp-taskflow/cpp-taskflow#148]
cpp-taskflow looks like exactly what i need, but i have trouble wrapping my head around exactly how i would use it. Sorry for this help request, hope its ok to post here.

I am looking to build up an image processing pipeline that will be run on each image provided by a camera. These images will be stored in a queue, and will come in at a faster rate (e.g. 500 Hz, so every 2 ms) than executing the whole pipeline will take (perhaps 10s of ms). Each image will traverse the exact same pipeline. I would like for this application to run real-time (with delay, assume we have enough cores) and thus need the built pipeline to run multiple times, and interleaved/overlapped (so next pipeline execution starts before previous is finished). This sounds similar to #66, which i understand is still open. I see also #39 which seems to provide an answer, but the syntax is no longer supported. As i currently can't compile v2.3.0 and HEAD (see #149), i am asking here first to check the concept and ask the questions i have.

Please let me know if this understanding is incorrect:
- I understand i would build up a ``tf::Taskflow`` representing my pipeline (not purely linear, has some operations that can run in parallel and are then gathered),
- To enable overlapping execution of multiple pipelines, i can submit the taskflow to the executor multiple times. Would i do this by simply calling ``tf::Executor::run_until()`` multiple times? If i understand the docs correctly, this would not work, because they say in chapter 2: "Issuing multiple runs on the same taskflow will automatically synchronize to a sequential chain of executions in the order of run calls." So the second run_until() wouldn't start until the first met its exit condition? EDIT: **ah, i understand the trick is to enqueue not the _the same_ pipeline multiple times, but _multiple identical_ pipelines on the executor. See below untested play code. I think that leaves only the below question.**
- how would i efficiently get my data into the pipeline? I envision that perhaps the first node would be popping an image of the images-to-be-processed-queue, and this pop would be blocking, suspending the queue until an image is available. Would that work or be a bad idea with your scheduler?

Thanks very much for your advice!

Starting code to work from, based on #39, hopefully updated to current taskflow version:
```c++
#include <taskflow/taskflow.hpp>
#include <thread>
#include <chrono>
using namespace std::literals::chrono_literals;

std::mutex logMutex;
void dispatchPipeline(tf::Executor& executor, int batch)
{
    auto taskMaker = [](std::string const& taskName, int batch, std::chrono::seconds sleepDur)
    {
        return [=]()
	{
            // Simulate some work
            std::this_thread::sleep_for(sleepDur);
            {
                std::lock_guard<std::mutex> lock(logMutex);
                std::cout << taskName << batch << '\n';
            }
        };
    };
    
    tf::Taskflow f{};
    auto[A, B, C, D] = f.emplace(
        taskMaker("A", batch, 1s),
        taskMaker("B", batch, 2s),
        taskMaker("C", batch, 3s),
        taskMaker("D", batch, 4s)
    );

    A.precede(B);  // B runs after A
    A.precede(C);  // C runs after A
    B.precede(D);  // D runs after B
    C.precede(D);  // D runs after C

    // Schedule this independent graph of tasks (so they start running)
    executor.run_n(f, 4, [=](){ std::lock_guard<std::mutex> lock(logMutex); std::cout << "end of four executions for batch" << batch << "\n"; });
}

int main()
{
    tf::Executor executor(4);

    // enqueue identical pipeline multiple times, for overlapped execution
    for (auto batch = 0; batch < 4; ++batch)
    {
        dispatchPipeline(executor, batch);
    }
    std::cout << "Tasks dispatched\n";
    executor.wait_for_all();
    std::cout << "All tasks finished\n";

    return 0;
}
```

**Comment by tsung-wei-huang** [comment]
@dcnieho Thanks for your questions. Yes, your understanding of `run_until` is correct. Multiple issues of runs on a taskflow will synchronize to sequential execution, one-by-one. 

Since your question is a bit complicated for me, let me try to rephrase it and see if I understand it correctly. Basically, what you want is a data pipeline-styled execution that can execute a sequence of items through a task chain with additional dependency on input data. For example, if I have a task graph `A->B->C` to feed 5 input images M1, M2, M3, M4, and M5, you desire each image to flow from A to C with simultaneous data dependency M1 before M2, M2 before M3, and so on. Do I understand your idea correctly?

**Comment by dcnieho** [comment]
@tsung-wei-huang Thanks! Is my understanding also correct that multiple enqueueing of unique (but the same) taskflows (as in the play code) will interleave/overlap in execution?

Your understanding of what i want is correct! But, to be sure, note that step A for M2 can start while A, B, or C is still running for M1--it can just start as soon as there is an image in the input queue again. That's what i mean with interleaved/overlapped execution.

**Comment by tsung-wei-huang** [comment]
@dcnieho Can you please elaborate a bit more on multiple enqueuing of taskflows? Since you use a plural,  I assume you are doing something like this:

```cpp
tf::Taskflow tf1, tf2, tf3, tf4;
executor.run(f1);
executor.run(f2);
executor.run(f3);
executor.run(f4);
```
In this case, tasks from tf1, tf2, tf3, tf4 can interleave, and there is no order which taskflow will finish first.

**Comment by dcnieho** [comment]
@tsung-wei-huang, yes i am testing to do something like that. Now that the code compiles, i see that it indeed works and interleaves well. I have one question left: my first task in each flow will have a blocking call, waiting for an element to become available in the input queue. Will that work fine/efficiently with your scheduler? I did notice some curious scheduling with the below code. If you have less threads than taskflows, then not all flows run in parallel. Run, for instance the below with 2 threads instead of 12: ``tf::Executor executor(2);``. Flows 0 and 1 now run through all their 3 iterations (``run_n`` with 3) before flows 2 and 3 start for the first time. I would expect that when waiting in task A for flows 0 and 1, task A for flow 2 could start running, etc. Does the wait in task A (and the others) prevent that whole thread from being used? Is there a way to yield and continue? Or is the solution simply: "spin up enough threads"?

For others reading this, my code above had an error, you need to keep the Taskflow alive until it has finished running. This works:
```c++
#include <taskflow/taskflow.hpp>
#include <thread>
#include <chrono>
using namespace std::literals::chrono_literals;

std::mutex logMutex;
void dispatchPipeline(tf::Executor& executor, int batch, tf::Taskflow* f_)
{
    auto taskMaker = [](std::string const& taskName, int batch, std::chrono::seconds sleepDur)
    {
        return [=]()
	    {
            // Simulate some work
            std::this_thread::sleep_for(sleepDur);
            {
                std::lock_guard<std::mutex> lock(logMutex);
                std::cout << taskName << batch << '\n';
            }
        };
    };
    
    auto[A, B, C, D, E] = f_->emplace(
        taskMaker("A", batch, 1s),
        taskMaker("B", batch, 2s),
        taskMaker("C", batch, 3s),
        taskMaker("D", batch, 3s),
        taskMaker("E", batch, 4s)
    );

    f_->broadcast(A, {B,C,D});  // B, C, D run after A
    f_->gather({ B,C,D }, E);   // E runs after B, C, D

    A.name("A");
    B.name("B");
    C.name("C");
    D.name("D");
    E.name("E");
    f_->name("Test batch "+std::to_string(batch));

    // Schedule this independent graph of tasks (so they start running)
    executor.run_n(*f_, 3, [=](){ std::lock_guard<std::mutex> lock(logMutex); std::cout << "end of four executions for batch" << batch << "\n"; });
}

int main()
{
    tf::Executor executor(12);

    auto start = std::chrono::steady_clock::now();

    // enqueue identical pipeline multiple times, for overlapped execution
    constexpr auto N = 4;
    tf::Taskflow taskflows[N] = {};
    for (auto batch = 0; batch < N; ++batch)
    {
        std::this_thread::sleep_for(batch*250ms);
        dispatchPipeline(executor, batch, &taskflows[batch]);
    }
    std::cout << "Tasks dispatched\n";

    // wait till all finished
    executor.wait_for_all();
    std::cout << "All tasks finished\n";
    auto end = std::chrono::steady_clock::now();

    // print how long it took
    std::cout << "Elapsed time in milliseconds : "
        << std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count()
        << " ms\n";

    // print the graph we've run
    std::cout << taskflows[0].dump() << std::endl;

    return 0;
}
```

**Comment by tsung-wei-huang** [comment]
@dcnieho , in response to your scheduling question, the short answer is probably no, because internally we use work-stealing with adaptive thread wake-up/sleep to balance the resource with dynamically generated parallelism. The entire process of stealing tasks is random and decentralized, and it is very difficult to get some determinism. That being said, we do guarantee no under- or over-subscription problems will happen (within a bounded interval).  At the scheduling level, we look at tasks, not taskflow. Which thread runs which task is completely decided by the work-stealing and the elapsed time of each execution. 

I hope this answers your question?

**Comment by dcnieho** [comment]
@tsung-wei-huang, thanks, yes you have. Thanks! So i guess i need to have a good balance between maximum number of waiting/blocked threads and total number of threads in the pool. No problem. And I will play with it a bit more with the possibilities, perhaps making the first task conditional and returning upon itself if no data in the queue instead of blocking would allow for flexible scheduling. I will just play with it, and report back for others if i find something useful. Thanks for your time!

**Comment by AA-Momeni** [comment]
> @tsung-wei-huang, thanks, yes you have. Thanks! So i guess i need to have a good balance between maximum number of waiting/blocked threads and total number of threads in the pool. No problem. And I will play with it a bit more with the possibilities, perhaps making the first task conditional and returning upon itself if no data in the queue instead of blocking would allow for flexible scheduling. I will just play with it, and report back for others if i find something useful. Thanks for your time!

Hello @dcnieho, I am also working on image processing pipeline. Please explain if you find a solution to this issue.

**Comment by dcnieho** [comment]
@AA-Momeni: sadly my focus has shifted since playing with this toolbox, and i still haven't shifted past playing. So nothing useful to say. I hope you will post here should you come up with something!
