### ISSUE TITLE
Head doesn't compile on MSVC

### ISSUE THREAD

**Issue by dcnieho** [cpp-taskflow/cpp-taskflow#149]
**Describe the bug**
When compiling simple.cpp, I get:
``C:\dat\projects\Tonii\TaskFlowTest\taskflow\taskflow\utility\object_pool.hpp(645): error C4703: potentially uninitialized local pointer variable 's' used``

This is in x64 debug mode, with /permissive- /std:c++latest
Complete command line:
``/JMC /permissive- /GS /W3 /Zc:wchar_t /I".\taskflow" /ZI /Gm- /Od /sdl /Fd"x64\Debug\vc142.pdb" /Zc:inline /fp:precise /D "_DEBUG" /D "_CONSOLE" /D "_UNICODE" /D "UNICODE" /errorReport:prompt /WX- /Zc:forScope /RTC1 /Gd /MDd /std:c++latest /FC /Fa"x64\Debug\" /EHsc /nologo /Fo"x64\Debug\" /Fp"x64\Debug\TaskFlowTest.pch" /diagnostics:column``

I get the same error both with current master HEAD as with the commit tagged v2.3.0

**edit: MSVC version: 19.4.5**

**Comment by tsung-wei-huang** [comment]
@dcnieho , I have commented out that line of the assertion. Would you please sync up with the master branch and test it again?

**Comment by dcnieho** [comment]
@tsung-wei-huang Thanks! I'm afraid i get the same error one the first next use of s now (with current as of this time HEAD):
``C:\dat\projects\Tonii\TaskFlowTest\taskflow\taskflow\utility\object_pool.hpp(650): error C4703: potentially uninitialized local pointer variable 's' used``

**Comment by dcnieho** [comment]
See [here](https://social.msdn.microsoft.com/Forums/en-US/5862b842-85d3-4229-adc4-46bd555de89c/error-c4703-potentially-uninitialized-local-pointer-variable-used?forum=winappswithnativecode) for a discussion of the specific error (warning). Note that the compiler command line is completely default for a new project made with VS19.4.5, except for the ``/std:c++latest`` switch, so other users will run into this error as well.

**Comment by tsung-wei-huang** [comment]
Hi @dcnieho if you change [this line](https://github.com/cpp-taskflow/cpp-taskflow/blob/5bf7965f89615a252eafd21e2b985be830b32cc4/taskflow/utility/object_pool.hpp#L588) to Block* s = nullptr, would you still see the error? Please let me know :)

**Comment by dcnieho** [comment]
Yes it does!

**Comment by tsung-wei-huang** [comment]
Fixed in the master branch. Thanks!
