### ISSUE TITLE
Broken compilation of 2.3.1 due to warning with MSVC 2017

### ISSUE THREAD

**Issue by ToniSimi** [cpp-taskflow/cpp-taskflow#153]
We are using MSVC 2017 in C++17 mode and our codebase follows the rule to treat warnings as errors. Release 2.3.1 (as well as the current codebase) includes a nameless struct which causes compilation to fail:

taskflow\utility\object_pool.hpp(86): warning C4201: nonstandard extension used: nameless struct/union

**Comment by tsung-wei-huang** [comment]
@ToniSimi fixed the warning. Please sync up with the master branch. Let me know if the problem is resolved.

**Comment by ToniSimi** [comment]
Yes, it compiles without warning. Not yet tested if everything still works but I would expect it does...
Thank you!
