### ISSUE TITLE
Relation to HeteroFlow?

### ISSUE THREAD

**Issue by dnbaker** [cpp-taskflow/cpp-taskflow#154]
Hi,

The library looks great, and I'm excited to try it. I wanted to check whether one framework should be preferred over another.

On the README.md, it mentions HeteroFlow as a project using cpp-taskflow, but I don't see any examples of taskFlow in that codebase.

It also shows an example of using cpp-taskflow for CUDA computation.

I have a variety of applications that would benefit from using cpp-taskflow, of which some would be a good fit for CUDA. If one wants to use one of the frameworks for heterogenous compute, should one be preferred?

Thanks!

Daniel

**Comment by tsung-wei-huang** [comment]
@dnbaker Hi Daniel, Heteroflow is a branch we did for experimenting concurrent CPU-GPU tasking, but it's now merged to cpp-taskflow. You can just stick with cpp-taskflow :)
