### ISSUE TITLE
Pinning a node to a specifc thread 

### ISSUE THREAD

**Issue by jcelerier** [cpp-taskflow/cpp-taskflow#159]
Hello,
does the library offer any guarantee on stability of the threads on which a given node would execute (at least in the static scheduling case) ? 

The reason being that some libraries sometimes attach data to the thread in which their constructor is called, and don't support these objects from ever being used from another thread.
Thus I'm wondering if this will already be safe, and if not, if there could be a way to specify that a given node should always execute on the same thread of the thread pool.

Thanks for the great lib !

**Comment by tsung-wei-huang** [comment]
Hi @jcelerier , in general, NO. We use a dynamic work-stealing  strategy in the scheduler for load balancing. Also, you may not be able to manipulate the worker which is internal to an executor. But I guess you can always to some client-side decision.

**Comment by jcelerier** [comment]
thanks for your answer, would there be any chance that the load balancing strategy be configurable in the future, e.g. through a template parameter or is it too entangled with the library ?

**Comment by tsung-wei-huang** [comment]
@jcelerier Maybe, in the past, we have tried using various strategies like this but most of them don't work out very well. However, it really depends on applications :) 

We have a very special work-stealing strategy that actually works out very well in most applications. Thanks for your advice!

**Comment by jcelerier** [comment]
> this but most of them don't work out very well.

For my case, I'd rather have the fallback possibility to use a strategy that does not work optimally than being forced to run single-thread though :p 

(The context is, I am using Qt's Javascript engine to run script snippets in different threads, intertwined with other C++ nodes. But Qt's javascript engine only supports being created & used from a single given thread for its lifetime, thus my issue. Well, I suppose I can check for thread id and recreate if I detect that a node has been moved...)

**Comment by tsung-wei-huang** [comment]
Yes, I think that could be a good solution, even though it's a bit workaround. But I will keep this use case in mind for future consideration...

**Comment by jcelerier** [comment]
ok thanks ! do I close the issue ?

**Comment by tsung-wei-huang** [comment]
Sure :)
