### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cpp-taskflow/cpp-taskflow#16]
I would like to point out that an identifier like “[`__throw__`](https://github.com/cpp-taskflow/cpp-taskflow/blob/9cf75aeec0fefa98e597b53169a615acec9e921e/taskflow.hpp#L44 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by twhuang-uiuc** [comment]
Good catch! I have renamed it to `throw_re` to reflect the `runtime_error` exception. Thanks.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/cpp-taskflow/cpp-taskflow/commit/cd201d2b8e1617c3bcb340b0a2ef30de82a1f383 "rename __throw__ to throw_re").
