### ISSUE TITLE
Unable to build if project depends on another library that uses an upstream MPark.Variant include

### ISSUE THREAD

**Issue by mydatamodels** [cpp-taskflow/cpp-taskflow#163]
**Describe the bug**
Our project uses cpp-taskflow and xtl libraries.
In xtl the same variant implementation is used, but with some subtle differences:

https://github.com/xtensor-stack/xtl/blob/master/include/xtl/xvariant_impl.hpp

The first thing that jumps out at me is that in the upstream the namespace is mpark and not nstd. Because of the header guards the first header included disables the other one, so for the client it's impossible to access to both namespaces.

**To Reproduce**
Just include both libraries and try to access both namespaces.

**Additional context**
I open the issue over you and not xtl because you changed the upstream :)

**Comment by tsung-wei-huang** [comment]
@mydatamodels Thank you for bringing this up. I have changed the `mpark` namespace into `tf::nstd` to make it stay under taskflow not being affected by any upstream code. Would you please sync up with the master and try again?

**Comment by mydatamodels** [comment]
This indeed did the trick! `#pragma once` for ever :)

Thanks and keep up the good work!
