### ISSUE TITLE
Narrowing conversions

### ISSUE THREAD

**Issue by matt77hias** [cpp-taskflow/cpp-taskflow#166]
I think most `unsigned` (int) types (especially in observer.hpp) can be replaced with `std::size_t` to fix all narrowing conversion warnings.

**Comment by tsung-wei-huang** [comment]
Yes I think in 2.4 I have replaced nearly all of them. But if you do see some, please let me know (or submit a pull request).

**Comment by tsung-wei-huang** [comment]
Thanks! I have merged the pull.
