### ISSUE TITLE
getenv

### ISSUE THREAD

**Issue by matt77hias** [cpp-taskflow/cpp-taskflow#168]
The only W4 MSVC warning that remains is:

Warning C4996 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use `_CRT_SECURE_NO_WARNINGS`.

The current use, however, is perfectly fine and technically not unsafe.

`getenv_s()` was added to C11 to let the caller provide a buffer, but will maybe be removed again.
So ideally `_dupenv_s` should be used _for MSVC_.

**Comment by tsung-wei-huang** [comment]
The warning is fixed at the master branch. Thanks!

**Comment by matt77hias** [comment]
Thanks for handling the MSVC case separately 👍
