### ISSUE TITLE
Adjust two constants in implementation of the function “throw_re”

### ISSUE THREAD

**Issue by elfring** [cpp-taskflow/cpp-taskflow#24]
I suggest to use constant characters instead of [passing string literals](http://en.cppreference.com/w/cpp/language/string_literal "Description for string literals") which contain only single characters.
Would you like to integrate [a source code adjustment](https://github.com/cpp-taskflow/cpp-taskflow/blob/8df87745966ceaf0b91e52b6d9ecc15c39c6c404/taskflow.hpp#L45 "Update candidate") like the following?

```diff
diff --git a/taskflow.hpp b/taskflow.hpp
index fd8e7f5..d30ea83 100644
--- a/taskflow.hpp
+++ b/taskflow.hpp
@@ -45,7 +45,7 @@ namespace tf {
 template <typename... ArgsT>
 inline void throw_re(const char* fname, const size_t line, ArgsT&&... args) {
   std::ostringstream oss;
-  oss << "[" << fname << ":" << line << "] ";
+  oss << '[' << fname << ':' << line << "] ";
   (oss << ... << std::forward<ArgsT>(args));
   throw std::runtime_error(oss.str());
 }
```

**Comment by twhuang-uiuc** [comment]
Can u submit a pull request? I can merge this change.

**Comment by twhuang-uiuc** [comment]
done. Thanks!
