### ISSUE TITLE
Adjust condition checks in implementation of the function “dump”

### ISSUE THREAD

**Issue by elfring** [cpp-taskflow/cpp-taskflow#25]
I suggest to [determine the emptiness of strings in a consistent way](http://en.cppreference.com/w/cpp/string/basic_string/empty "Description for std::basic_string::empty()") for a succinct data output.
How do you think about to integrate [a source code adjustment](https://github.com/cpp-taskflow/cpp-taskflow/blob/b3b0eb270b5fe51666c0043b63bb674e6ca2cde6/taskflow.hpp#L1011 "Update candidate") like the following?

```diff
diff --git a/taskflow.hpp b/taskflow.hpp
index d30ea83..ae3ae89 100644
--- a/taskflow.hpp
+++ b/taskflow.hpp
@@ -1017,20 +1017,13 @@ std::string BasicTaskflow<F>::dump() const {
   os << "digraph Taskflow {\n";
   
   for(const auto& node : _nodes) {
-
-    os << "  \"";
-    if(!node.name().empty()) os << node.name();
-    else os << &node;
-    os << "\";\n";
+    os << "  \"" << (node.name().empty() ? &node : node.name()) << "\";\n";
 
     for(const auto s : node._successors) {
-      os << "  \"";
-      if(!node.name().empty()) os << node.name();
-      else os << &node;
-      os << "\" -> \"";
-      if(s->name() != "") os << s->name();
-      else os << s;
-      os << "\";\n";  
+      os << "  \"" << (node.name().empty() ? &node : node.name())
+         << "\" -> \""
+         << (s->name().empty() ? s : s->name())
+         << "\";\n";  
     }
   }
 
```

**Comment by elfring** [comment]
[My software refactoring idea](http://computersirkiclass.com/?codesheet=ternary-operator-within-cout-chain-for-selective-printing&tag=cp005-operators "Using the ternary operator for selective data output") needs [further development considerations](http://en.cppreference.com/w/cpp/language/operator_other#Conditional_operator "Description for the conditional operator").
Would you like to [reconsider any additional design options](https://stackoverflow.com/questions/13050138/ternary-operator-and-function-signature#answer-13050200 "Ternary operator and function signature")?

**Comment by twhuang-uiuc** [comment]
This has been done. Thanks for your idea :)

**Comment by elfring** [comment]
* Did you take any look at [the linked software development concerns](https://stackoverflow.com/questions/13050138/ternary-operator-and-function-signature "Ternary operator and function signature")?
* Would you like to add another test case?
* How do you think about [further adjustments and corresponding extensions](https://github.com/cpp-taskflow/cpp-taskflow/commit/f452f047d5fc7863123c4a4f95a2cf0118b0bd17#diff-ad4f88ac4b041650a02e044706f17316L1036 "Update candidate")?

**Comment by elfring** [comment]
The following change approach is usable to some degree.

```diff
diff --git a/taskflow.hpp b/taskflow.hpp
index d30ea83..8a2e314 100644
--- a/taskflow.hpp
+++ b/taskflow.hpp
@@ -456,6 +456,7 @@ class BasicTaskflow {
     size_t num_workers() const;
     size_t num_topologies() const;
 
+    static std::string check_name(Node const & n);
     std::string dump() const;
 
   private:
@@ -1007,36 +1008,34 @@ void BasicTaskflow<F>::_schedule(Node& task) {
   });
 }
 
+std::string convert_address(void const * x) {
+  std::ostringstream os;
+  os << x;  
+  return os.str();
+}
+
+template <typename F>
+std::string BasicTaskflow<F>::check_name(Node const & n) {
+  return n.name().empty() ? convert_address(&n) : n.name();
+}
+
 // Function: dump
 // Dumps the taskflow in graphviz. The result can be viewed at http://www.webgraphviz.com/.
 template <typename F>
 std::string BasicTaskflow<F>::dump() const {
-
-  std::ostringstream os;
-
-  os << "digraph Taskflow {\n";
+  std::string os("digraph Taskflow {\n");
   
   for(const auto& node : _nodes) {
-
-    os << "  \"";
-    if(!node.name().empty()) os << node.name();
-    else os << &node;
-    os << "\";\n";
+    std::string x("\"");
+    x.append(check_name(node)).push_back('"');
+    os.append(x).push_back('\n');
 
     for(const auto s : node._successors) {
-      os << "  \"";
-      if(!node.name().empty()) os << node.name();
-      else os << &node;
-      os << "\" -> \"";
-      if(s->name() != "") os << s->name();
-      else os << s;
-      os << "\";\n";  
+      os.append(x).append(" -> \"").append(check_name(*s)).append("\"\n");
     }
   }
 
-  os << "}\n";
-  
-  return os.str();
+  return os.append("}\n");
 }
 
 //-------------------------------------------------------------------------------------------------
```


I find that further software adjustments will be needed so that [escaping of double quotes will be taken into account](https://graphviz.gitlab.io/_pages/doc/info/lang.html "Description for the DOT language").

**Comment by twhuang-uiuc** [comment]
It would be better you can submit a pull request if you would like this to be merged. This will at least go through CI test. The last change you suggested was not compilable.

**Comment by elfring** [comment]
>This will at least go through CI test.

* I tried to point development concerns out (before you comitted another change combination).
* Does [this software area need any extensions](https://github.com/cpp-taskflow/cpp-taskflow/commit/7b5640e34afec911251500db9e3ab6013fe4ea7e "added debug example and fix dump error")?


>The last change you suggested was not compilable.

My update suggestion for the increased usage of [the “shift operator”](https://stackoverflow.com/questions/12233710/how-do-i-use-the-ostringstream-properly-in-c "How do I use the ostringstream properly in c++?") (together with [the “conditional operator”](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0917r1.pdf "Proposal “Making operator?: overloadable” by Matthias Kretz from 2018-05-06")) looked too promising for a moment.
The C++ compiler could only point questionable implementation details out after the addition of a test case for [the file output example](https://github.com/cpp-taskflow/cpp-taskflow#debug-a-taskflow-graph "Debug a taskflow graph").
