### ISSUE TITLE
Fix add_test() calls in a CMake script

### ISSUE THREAD

**Issue by elfring** [cpp-taskflow/cpp-taskflow#26]
[The prefix “`${PROJECT_SOURCE_DIR}/unittest/`” was specified](https://github.com/cpp-taskflow/cpp-taskflow/blob/8df87745966ceaf0b91e52b6d9ecc15c39c6c404/CMakeLists.txt#L79 "Update candidate") for [calls of the CMake command “`add_test`”](https://cmake.org/cmake/help/v3.11/command/add_test.html "Description for add_test()").
I suggest to delete it there.

**Comment by elfring** [comment]
I find [the use of a CMake variable like “`PROJECT_BINARY_DIR`”](https://cmake.org/cmake/help/v3.11/variable/PROJECT_BINARY_DIR.html "Description for a CMake variable") for generated files more appropriate than referring to the variable “`PROJECT_SOURCE_DIR`” in [the affected build script](https://github.com/cpp-taskflow/cpp-taskflow/blob/8df87745966ceaf0b91e52b6d9ecc15c39c6c404/CMakeLists.txt#L74 "Update candidate").

**Comment by twhuang-uiuc** [comment]
Not sure if I understand you question. Would you please create either a git diff or a pull request?

**Comment by elfring** [comment]
How do you think about to replace a questionable directory specification by a CMake variable which provides safe information?

**Comment by elfring** [comment]
Would you like to distinguish better between directories for generated files and source files?
