### ISSUE TITLE
OpenMP Comparison in matrix.cpp is unfair

### ISSUE THREAD

**Issue by jcownie-intel** [cpp-taskflow/cpp-taskflow#29]
**Describe the bug**
The OpenMP code in example/matrix.cpp is exceptionally naive. You know that the matrices are of different sizes and will therefore take different times to multiply, yet you are using the default (i.e. static in all compilers of which I am aware) loop schedule. To be fair you should at least use `schedule(dynamic)` on all of the parallel for statements. You could also experiment with `schedule(nonmonotonic:dynamic)` if you have a modern compiler. 

You could also reduce the number of fork/join operations by using code more like this
```C++
void openmp(const std::vector<size_t>& D) {

  std::cout << "========== OpenMP ==========\n";

  auto tbeg = std::chrono::steady_clock::now();

  std::vector<matrix_t> As(D.size());
  std::vector<matrix_t> Bs(D.size());
  std::vector<matrix_t> Cs(D.size());

  std::cout << "Generating matrix As ...\n";

  #pragma omp parallel
  {
    #pragma omp for schedule(dynamic)
    for(int j=0; j<(int)D.size(); ++j) {
      As[j] = random_matrix(D[j]);
    }

    #pragma omp single
      std::cout << "Generating matrix Bs ...\n";

    #pragma omp for schedule(dynamic)
    for(int j=0; j<(int)D.size(); ++j) {
      Bs[j] = random_matrix(D[j]);
    }

    #pragma omp single
      std::cout << "Computing matrix product values Cs ...\n";

    #pragma omp for schedule(dynamic), nowait
    for(int j=0; j<(int)D.size(); ++j) {
      Cs[j] = As[j] * Bs[j];
    }
  }

  auto tend = std::chrono::steady_clock::now();

  std::cout << "OpenMP takes "
            << std::chrono::duration_cast<std::chrono::milliseconds>(tend-tbeg).count()
            << " ms\n";
}
```
Or you could experiment with omp taskloop :-)

**To Reproduce**
1. Read the code
2. Be amazed at its naivety

**Expected behavior**
Be fair in your comparisons.

**Comment by twhuang-uiuc** [comment]
Thanks for your insightful comments! Yes you are right and we were aware of this. However, the purpose here is not to demonstrate the speed of OpenMP, but the way it describes task dependencies. Also, please don't be biased by this simple example. Think of combing this matrix computation workload with other applications where you have many dependencies. It becomes very difficult to use OpenMP tasking pragma, i.e., `in[...]`, `out[...]`, `inout[...]`).

**Comment by jcownie-intel** [comment]
But in that case, why are you not using OpenMP tasks and dependencies? You can't claim to be showing how OpenMP handles task dependencies without even using them! 

If all the code does is print performance numbers, that is what people will compare. So if that wasn't the point you are trying to make you need to say so, and have code which can make the point you want to make. This OpenMP code clearly says absolutely nothing about OpenMP tasks or how task dependencies are expressed, since it doesn't include them, so cannot be used to argue the point you claim you want to make!

**Comment by twhuang-uiuc** [comment]
The reason to not do this is it is very difficult and almost impossible to do this using OpenMP tasking, especially you have runtime dependencies. We do agree with the confusion point. We will consider removing this part from the example or moving it to other places. Thanks!

**Comment by twhuang-uiuc** [comment]
Now OpenMP code is removed. We will create another repo to place all benchmarks and show the comparisons.

**Comment by jcownie-intel** [comment]
Thanks!
