### ISSUE TITLE
Can this be used to run a "single" task a thousand times? (each time with different arguments)

### ISSUE THREAD

**Issue by markg85** [cpp-taskflow/cpp-taskflow#36]
Hi,

I have a fairly simple task: make thumbnails of a thousand large images.
Right now i'm using a thread pool which works great! I basically have one function that accepts two input arguments (the source of the large image and the destination of the thumbnail), that is then added to a queue which is then emptied by the threadpool.

But how would you do such a thing in this tasks library? Is it even intended to be used like that, and if so, how?
An example would be really great :)

I've been looking at the parallel_for example but i don't quite see how i would apply that to my case yet.

Cheers,
Mark

**Comment by twhuang-uiuc** [comment]
Hi, if your application has no dependency and you just need a pool of threads to do your job simultaneously, you can just use our built-in threadpool.

```cpp
tf::Threadpool tp(4);  // create a threadpool of 4 worker threads

tp.silent_emplace([] () { /* task 1*/ });    // silent_emplace won't return a future
tp.silent_emplace([] () { /* task 2*/ });
... add more tasks

std::future<int> fu1 = tp.emplace([](){ return 1; })  // emplace returns a future
... add more tasks
```

**Comment by totalgee** [comment]
Just a clarification about why you added the `future<int>` at the end of your threadpool example...I assume you did this so you could "check" when all the tasks have completed, without creating futures for each of them?  (As an unrelated comment, it wouldn't have to be `future<int>`; it might as well just be `future<void>`.)

However, calling "get" on this task's future won't guarantee that all the earlier-scheduled tasks have completed, right? Tasks are scheduled in the pool of workers in order they're "emplaced", so that last-added task will indeed be *scheduled* last to a worker thread, but there's no guarantee the last few other tasks will have finished by the time its future is ready...

Maybe what you mean is: since `tp.shutdown()` is called implicitly by the `tf::Threadpool` destructor, as long as all tasks in the queue have been assigned to a worker already(!), this will ensure all tasks are completed when the shutdown method finishes running.

So you'd have to add to your example (if it's important to ensure all the tasks are complete at a certain point):
```cpp
  fu1.get();
  // At this point it's still not guaranteed all tasks have completed...
  tp.shutdown();  // or just leave tp's scope so its destructor is called!
  // ...at this point, all the tasks should be done.
```

Do I understand correctly?

**Comment by twhuang-uiuc** [comment]
@thuang19  Yes, you are correct. You will need to call get somewhere in your control in order to get the return value when the task finishes. This is the purpose of calling `async`.

**Comment by markg85** [comment]
@twhuang-uiuc, thank you for your reply!

The API way of handling this looks slightly inconvenient though. Having to call .get() on the future and having to call shutdown on the task object.

Isn't there a more natural way of doing that?
tf::wait_for_all() won't work?

Also, this structure (as with most threadpools out there really) will create the function for as many times as it needs to be executed and pass in the arguments i want. That works just fine, but sounds wasteful to me. It would be ideal if you only made the function object for as many threads as provided in the ThreadPool constructor and re-use the functions (or threads even), just with different arguments. I guess this is heavily reliant on the type of work you'd do and would basically limit a threadpool to one type of work only. So 1 pool with n-th threads.

**Comment by twhuang-uiuc** [comment]
Hi @markg85 , would you provide a sequential code example on your flow so I can provide more detailed help for u? If you don't need future, you should use `silent_async` and so on.

**Comment by markg85** [comment]
Hi @twhuang-uiuc , sure. It uses Qt though. Right now it's merely an experiment at quickly generating thumbnails for 4k wallpapers.


**The generic part:**
`
void createThumbnail(const QString file)
{
  QSize size = QSize(256, 256);
  qDebug() << "Loading: " << file;
  QImage image(file);
  QImage scaledImage = image.scaled(size, Qt::KeepAspectRatio);

  QCryptographicHash md5(QCryptographicHash::Md5);
  md5.addData(file.toLocal8Bit());
  const QString hexValue = md5.result().toHex();
  QString resFileName = QString("/home/mark/Wallpapers/4k_thumbs/%1.webp").arg(hexValue);
  scaledImage.save(resFileName, "WEBP", 75);
  qDebug() << "Saved as thumbnail:" << file;
}

QDir dir("/home/mark/Wallpapers/4K Wallpapers");
dir.setFilter(QDir::Files | QDir::NoDotAndDotDot);
QStringList files = dir.entryList();
`

**The sequential code addition:**
`
foreach (QString file, files)
{
  QString composedFullPath = dir.absolutePath() + "/" + file;
  createThumbnail(composedFullPath);
}
`

**The parallel code instead of the sequentail one:** (uses the ThreadPool from http://roar11.com/2016/01/a-platform-independent-thread-pool-using-c14/ , not yours yet)
`
ThreadPool pool(std::thread::hardware_concurrency() + 2);
std::vector<ThreadPool::TaskFuture<void>> thumbnailJobs;

foreach (QString file, files)
{
  QString composedFullPath = dir.absolutePath() + "/" + file;
  thumbnailJobs.push_back(pool.submit(createThumbnail, composedFullPath));
}

for(auto& item: thumbnailJobs)
{
  item.get();
}
`

The above all works and thus far can also work with your library.
The last request a made (to reuse threads) would imho look somewhat like this (hypothetical code!):

`
tf::Threadpool tp(4);
tp.silent_emplace(createThumbnail);
tp.silent_emplace(createThumbnail);
tp.silent_emplace(createThumbnail);
tp.silent_emplace(createThumbnail);

foreach (QString file, files)
{
  QString composedFullPath = dir.absolutePath() + "/" + file;
  tp.packaged_params(composedFullPath);
}

tp.execute();
`

Now you **only** have 4 threads. As a thread gets available it's called with the function that already lives in that thread (createThumbnail) with the next packaged parameters that haven't been processed yet.
That way you only ever create 4 threads (or however many you provided in the Threadpool constructor) which will avoid creating thousands of thread instances over the execution time. For large running jobs that is probably no issue as thread creating time is likely comparatively nothing to a large job. But for tiny you just want to use all cores to process all the tasks as quickly as possible the thread creation time probably (i haven't benchmarked that) begins to add up and cost a notable slice of the overall running time. So this is a very nice performance optimization.

I hope i'm not to vague in this request :)

**Comment by clin99** [comment]
Hi @markg85    I think cpp-Taskflow could also work in this case if I understand correctly:

```cpp
  tf::Taskflow tf(4);

  for(size_t i=0; i<files.size(); i++){
    tf.silent_emplace([&, i=i](){ 
       // Assume each Thumbnail can be created independently to each other
       QString composedFullPath = dir.absolutePath() + "/" + file[i];
       createThumbnail(composedFullPath);
    }); 
  };  

  tf.wait_for_all();    // Wait for all tasks finish
```
Please correct me if this does not fit your need.

Thanks!

**Comment by totalgee** [comment]
This is what I was going to suggest -- just use a Taskflow rather than Threadpool, then call wait_for_all() at the end. No need for futures. It might be nice to add a wait_for_all() to Threadpool too, though, for such simple cases...

**Comment by twhuang-uiuc** [comment]
@markg85 , I will suggest the following modification based on your code:

```cpp
  tf::Taskflow tf(std::thread::hardware_concurrency());
  tf.parallel_for(files.begin(), files.end(), [&] (const auto& file) {
    QString composedFullPath = dir.absolutePath() + "/" + file;
    createThumbnail(composedFullPath);
  });  // each thread execute one iteration
  tf.wait_for_all();
```

By default, `parallel_for` will create one task for each iteration at `file`. In the above example, there is a total of `files.size()` tasks. You can pass an additional argument of size to group tasks. For example, the following code gives you `files.size()/4` tasks.

```cpp
  tf::Taskflow tf(std::thread::hardware_concurrency());
  tf.parallel_for(files.begin(), files.end(), [&] (const auto& file) { 
    QString composedFullPath = dir.absolutePath() + "/" + file;
    createThumbnail(composedFullPath);
  }, 4); // each thread execute 4 iterations
  tf.wait_for_all();
```

You can also give `0` and taskflow will do even partition for you. You can refer to the README for more details :)

**Comment by markg85** [comment]
@twhuang-uiuc they all work an all with roughly the same performance.
I did look at the parallel_for as one of the first options, but the way the documentation is written lead me to think that it wasn't applicable to my usecase. I'm glad it is though as it simplifies it even more :)

Perhaps the whole documentation could be updated a little for the non-task based approach. Or in other terms, the approach where you just want to run one taks in parallel without any dependency graphs.

**Comment by twhuang-uiuc** [comment]
Hi @markg85 , thanks for your feedback! I will start to work on a more detailed doc page or perhaps a page `taskflow best practice` talking about this - :)

**Comment by markg85** [comment]
That's great! Glad i could help i guess, hehe.
Closing this issue now as it has been solved in a bunch of different ways already :)
