### ISSUE TITLE
Disposal of completed tasks and destruction of task trees.

### ISSUE THREAD

**Issue by ForgeMistress** [cpp-taskflow/cpp-taskflow#45]
I've been trying to figure out where I am able to remove tasks from the graph or how the lifetimes of the tasks are managed, but this library doesn't seem to make it obvious where that is. The reason for this is that I want to be able to build temporary graphs for asynchronous resource loading that I can then discard once they've been processed. The graph would be perfect since I can use the graph to ensure resources that have dependencies are loaded in the correct order. However, once the resources are loaded, it is safe for the graph to be cleaned up to keep memory usage low.

Are there any examples that you could provide that display this type of behavior? It seems like the only way for me to do this would be to discard the Taskflow object entirely and construct a new one, however that seems a little bit excessive since I feel like there should be a way to selectively remove branches of tasks from the graph.

**Comment by twhuang-uiuc** [comment]
Hi @ForgeMistress , the lifetime of a task sticks with its graph. A task is not destroyed until its graph is cleared. Consider the following example:
```cpp
1: auto A = tf.silent_emplace([](){});
2: auto B = tf.silent_emplace([](){});
3: A.precede(B);
4: tf.wait_for_all();
```
The lifetime of task A and task B exist until `wait_for_all` returns. Task A is still alive even when task B is running. What we mean by alive is, we do not destroy its internal data structure, including those captured by the lambda. The method `wait_for_all` will dispatch the graph and then destroy the graph when it finishes. 

I hope this helps.

**Comment by ForgeMistress** [comment]
So the process _is_ destructive. Excellent. That clears up a lot, actually. I was under the impression that the graphs remain between iterations for some reason. Thanks a lot for the clarification.

**Comment by twhuang-uiuc** [comment]
@ForgeMistress  Thank you for bringing this up. I have added this to our cookbook [Lifetime of a Graph](https://github.com/cpp-taskflow/cpp-taskflow/blob/master/doc/cookbook/dispatch.md#lifetime-of-a-graph) with a coupled of example to demonstrate the lifetime of a graph. Please read it and let me know it that clarifies your question.

**Comment by ForgeMistress** [comment]
Ok, then this brought up a new question I have. If graphs are dispatched asynchronously, the internal graph remains. Could the graph be dispatch()ed again after that?

**Comment by clin99** [comment]
@ForgeMistress  Currently a graph can only be executed once. After a graph is dispatched, you need to start with a new graph construction.

**Comment by ForgeMistress** [comment]
Ok, thanks. The wording in the cookbook link led me to think that that wasn't the case. Might want to clarify that.

**Comment by twhuang-uiuc** [comment]
Hi @ForgeMistress  thanks for the point. Yes, each taskflow object has only one graph at a time. Every task/dependency construction refers to the present graph in the taskflow object. When you dispatch it, the taskflow object will start with a new graph data structure and so on.

**Comment by ForgeMistress** [comment]
With the help you guys provided me, I was able to rewrite my asynchronous resource loader to use taskflow, and I plan on utilizing the library for update processes and render processes as well since my project will be running on Vulkan for PC platforms. Not sure what I'd do with PS4 if I ever get that far (I _assume_ they have threaded rendering, however I am not entirely sure since I haven't worked with the platform outside of the inhouse engine at my old job, and that was all wrapped up and I never touched the platform code). I greatly appreciate youralls help.

**Comment by twhuang-uiuc** [comment]
Sure @ForgeMistress . Please let us know if you run into other issues. Is your implementation available on the Github? If yes, we would like to acknowledge your effort on using cpp-taskflow.

**Comment by ForgeMistress** [comment]
It is indeed. At the moment, the resource management system is written to operate on a single thread because I realized that it makes more sense to utilize resource load operations within other task dispatches rather than try to abstract the Taskflow API away. Keeps the resource loader code simple.
