### ISSUE TITLE
Taskflow reuse

### ISSUE THREAD

**Issue by BenjaminNavarro** [cpp-taskflow/cpp-taskflow#49]
I came across cpp-taskflow recently and I find it very interesting and well designed. However, from my point of view, it would be great to have the possibility to reuse a Taskflow graph after its completion.

To give a bit of background, I work on robot control and we always have a bunch of stuff to compute in a real time loop (up to 1kHz/1ms) in order to send the robot(s) a new command. Taskflow would fit perfectly to describe and perform all the computations but having to reconstruct the graph at each iteration is not very elegant and may also bring some latencies due to the dynamic memory allocations that happen behind the scene.

Is it something that could be implemented in cpp-taskflow?

**Comment by BenjaminNavarro** [comment]
Basically yes. 

Not sure about the `std::string` identifier though. If it is only generated by `make_framework()` and passed to `run()`, why not using some kind of integer value instead? I don't see the added benefit of creating, storing and comparing strings here. Unless we can do something like:
```cpp
auto A = tf.silent_emplace([] () {});
tf.make_framework("foobar");
tf.run("foobar");
```
In that case using strings can be a good idea.

**Comment by twhuang-uiuc** [comment]
Hi @BenjaminNavarro , yes, that was just an example. We will discuss some options and keep you posted. Thank you!

**Comment by BenjaminNavarro** [comment]
Thanks @twhuang-uiuc, that's great news ! 

Can you also confirm me that in this scenario the threads in the tread pool won't be created and destroyed at each run?

**Comment by twhuang-uiuc** [comment]
@BenjaminNavarro The threadpool's life time is bound to a taskflow object, unless you define your own executor. It has nothing to do with the framework :)

**Comment by digitalmonkey** [comment]
I second the request for taskflow reuse. Something as simple as:

TaskFlow::rewind() or TaskFlow::reset()

Which would reinitialize the original taskflow back to the start again. In my use case, I perform a repetitive update() loop on a bunch of tasks, but they must be performed in a specific order. These tasks must be run every loop over and over.

**Comment by digitalmonkey** [comment]
Another possibility is to set an option for the TaskFlow to make it non-malleable, so it doesn't remove the graph when its done.

**Comment by twhuang-uiuc** [comment]
Hi @BenjaminNavarro @digitalmonkey , yes, we agreed with you on the graph reuse. We are currently working on this feature and it may take sometime to finish. We want everything to be general and extensible from the software engineering point of view. We will have a new feature called "framework". This allows user to own a task dependency graph and create its own compute pattern. At the same time, we will extend the taskflow object's graph to be reusable. We thank for your support for Cpp-Taskflow. Please stay tuned.

**Comment by BenjaminNavarro** [comment]
That's great news, can't wait to try that!

**Comment by digitalmonkey** [comment]
These are welcome updates and eagerly look forward to trying them out.
Thanks for the quick response and a great library.
Victor

**Comment by hchevanne** [comment]
I join the list of applicants.
In my case, it is a custom AI application in which the same graph must be run on a set of input data.
Can we expect a next update?
Thanks.

**Comment by twhuang-uiuc** [comment]
Hi @BenjaminNavarro @hchevanne @digitalmonkey , we just released Cpp-Taskflow v2.1.0 from the master branch. We have included a new feature called `tf::Framework` to enable the reuse of a task dependency graph. Please refer to the following information:

[release note 2.1.0](https://cpp-taskflow.github.io/cpp-taskflow/release-2-1-0.html)
[Framework tutorial](https://cpp-taskflow.github.io/cpp-taskflow/chapter7.html)

We have been trying hard to enable this new capability. One thing to note is, `emplace` and `silent_emplace` are now doing the same thing. Calling `emplace` no longer gives you a future object to access the return value. 

Please give it a try! We are still experimenting the Framework feature and are welcome any suggestions/feedback.

**Comment by digitalmonkey** [comment]
Thank you Tsung-Wei,
I’ll try it out!
Victor

**Comment by hchevanne** [comment]
Thanks a lot Tsung-Wei. Great job.
I'll try it right away!

**Comment by BenjaminNavarro** [comment]
Just to say that I started using the `tf::Framework` recently and it works just fine. Great job guys!

**Comment by twhuang-uiuc** [comment]
@BenjaminNavarro  Please let us know if you have any questions in the future (or anything you think can improve the library) :)

**Comment by pgruenbacher** [comment]
So I make a bench test to just see the cost of initializating an empty Taskflow and I'm seeing quite a high release cost of 366 microseconds... 

```
void makeTaskflow(benchmark::State& state) {
  Registry reg;
  // curious cost of making a taskflow instance each step...
  while (state.KeepRunning()) {
    tf::Taskflow tf;
  }
}
```
```
makeTaskflow                        549 us        366 us       1971
````

I'm guessing cause it's making a new graph each time? For something like an empty #pragma omp parallel sections , it's only 2 microseconds....

**Comment by pgruenbacher** [comment]
hm I see, the time just scales with the number of executor threads being used....
well it'd still be nice to be able to reset the taskflow so that the threads aren't being re-instantiated every step.

**Comment by pgruenbacher** [comment]
sorry nvm again I realize I can just re-use the same taskflow instance to run the same framework multiple times without having to reinstantiate the taskflow instance.

**Comment by tsung-wei-huang** [comment]
@pgruenbacher , yes, we added the framework to support reusable and composable task dependency graphs :) This is what you need.
