### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by victorusu** [cpp-taskflow/cpp-taskflow#50]
Hi, have you considered to have releases? 

If so, when do you plan to have the first one?
If not, can you make release?

Thanks.

**Comment by twhuang-uiuc** [comment]
Hi @victorusu , currently, the newest version refers to the `master` branch, while `dev` is a place for development. We will have a release soon after we work out the entire documentation (API doc). Before that, please refers to the master branch - many things are stable.
