### ISSUE TITLE
separate declaration and implementation

### ISSUE THREAD

**Issue by lifeiteng** [cpp-taskflow/cpp-taskflow#55]
**Is your feature request related to a problem? Please describe.**
I want to use TaskFlow in a C++ project which depends on TensorFlow. When compiling the Op & Kernel with `c++17`, there is a problem https://github.com/tensorflow/tensorflow/issues/23561

**Describe the solution you'd like**
separate declaration and implementation, e.g.
```
# depends
g++ -std=c++17 taskflow/graph taskflow/threadpool ..

# keep header simple
g++ -std=c++11 taskflow/taskflow.hpp ..
```
In this way, I can use taskflow/taskflow.hpp with TensorFlow without c++17

**Describe alternatives you've considered**
separate declaration and implementation in Ops & Kernels, there is a lot of work to do.

**Additional context**
Can you give some suggestions for doing this (separate declaration and implementation).

**Comment by twhuang-uiuc** [comment]
Hi @lifeiteng  I am not sure if I understand your question. What is your compiler version in this example? To compile taskflow you need at least g++7.3 or 8.0 (recommended). There are many known bugs in -std=c++17 in g++7 series. Also, you can simply use `-I` to specify the header path of cpp-taskflow rather than giving files one by one.
```
g++ -I /path/to/your/taskflow your_code.cpp
```

**Comment by lifeiteng** [comment]
> Hi @lifeiteng Thanks for your interests in Cpp-Taskflow! I am not sure if I understand your question. What is your compiler version in this example? To compile taskflow you need at least g++7.3 or 8.0 (recommended). There are many known bugs in -std=c++17 in g++7 series. Also, you can simply use `-I` to specify the header path of cpp-taskflow rather than giving files one by one.
> 
> ```
> g++ -I /path/to/your/taskflow your_code.cpp
> ```
Clang on OSX or g++ on Ubuntu
I want to use TaskFlow to speed up some custom TensorFlow Kernels. 
There is a lot of problems when compiling with custom TensorFlow Kernels, which caused by `-std=c++17` FLAG.

**Comment by clin99** [comment]
Hi @lifeiteng , according to the reply of the issue https://github.com/tensorflow/tensorflow/issues/23561, the best solution is to rebuild TensorFlow from source with the `-std=c++17` flag.   If you are using a TensorFlow prebuilt binary (i.e. `pip install`), then you can use the workaround suggested under the issue:

Add following two lines on top of your custom kernel file:
```cpp
#include "absl/base/config.h"
#undef ABSL_HAVE_STD_STRING_VIEW
```

Here is an example (zero_out.cc) modified from the [TensorFlow Guide](https://www.tensorflow.org/guide/extend/op):
```cpp
#include "absl/base/config.h"                                                                                                     
#undef ABSL_HAVE_STD_STRING_VIEW

#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"
#include <taskflow/taskflow.hpp>

using namespace tensorflow;

REGISTER_OP("ZeroOut")
    .Input("to_zero: int32")
    .Output("zeroed: int32")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {

      c->set_output(0, c->input(0));
      return Status::OK();
    }); 

class ZeroOutOp : public OpKernel {
 public:
  explicit ZeroOutOp(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    // Use cpp-taskflow inside kernel
    tf::Taskflow tf; 
    tf.silent_emplace([](){ std::cout << "Hello World\n"; }); 
    tf.wait_for_all();

    // Grab the input tensor
    const Tensor& input_tensor = context->input(0);
    auto input = input_tensor.flat<int32>();
    
    // Create an output tensor
    Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
                                                     &output_tensor));
    auto output_flat = output_tensor->flat<int32>(); 
    
    // Set all but the first element of the output tensor to 0.
    const int N = input.size();
    for (int i = 1; i < N; i++) {
      output_flat(i) = 0;
    } 
    
    // Preserve the first input value if possible.
    if (N > 0) output_flat(0) = input(0);
  } 
};

REGISTER_KERNEL_BUILDER(Name("ZeroOut").Device(DEVICE_CPU), ZeroOutOp);                   
```

To compile this example (zero_out.cc):
```bash
TF_CFLAGS=( $(python3.5 -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python3.5 -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
g++ -std=c++17 -I ./cpp-taskflow -shared zero_out.cc -o zero_out.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2
```

Then you can use `tf.load_op_library('./zero_out.so')` to load the custom kernel in your Python application. This might be easier than separating declaration and implementation. 

Thanks.

**Comment by lifeiteng** [comment]
@clin99 Thanks.
I speed some hours wrapping TaskFlow to avoid the compile error.

In the first step, I want to use TaskFlow to parallel Matrix * Matrix, like this:
```
tf::Taskflow tf(num_threads);
// C_t = A_t * B
// A is batch_size x 1024]
// B is 1024 x 3072
B1, B2, B3 ... = Split(B, num_threads)
for (int64 t = 0; t < time_steps; ++t) {  // cannot parallel all time steps
    tf.parallel_for({1, 2, ..., num_threads},
        C_t = A_t * B_1, 1);
    auto future = tf.dispatch();
    future.get();
    // .....
    O_t = Ct * Matrix
}
```
but it's **much slower** than single thread.
If parallel all time steps(e.g. comment out `auto future = tf.dispatch(); future.get();`), the speedup ratio is about `num_threads-1`.

**Comment by lifeiteng** [comment]
> @clin99 Thanks.
> I speed some hours wrapping TaskFlow to avoid the compile error.
> 
> In the first step, I want to use TaskFlow to parallel Matrix * Matrix, like this:
> 
> ```
> tf::Taskflow tf(num_threads);
> // C_t = A_t * B
> // A is batch_size x 1024]
> // B is 1024 x 3072
> B1, B2, B3 ... = Split(B, num_threads)
> for (int64 t = 0; t < time_steps; ++t) {  // cannot parallel all time steps
>     tf.parallel_for({1, 2, ..., num_threads},
>         C_t = A_t * B_1, 1);
>     auto future = tf.dispatch();
>     future.get();
>     // .....
>     O_t = Ct * Matrix
> }
> ```
> but it's **much slower** than single thread.
> If parallel all time steps(e.g. comment out `auto future = tf.dispatch(); future.get();`), the speedup ratio is about `num_threads-1`.

**Platform: Ubuntu 16.04**
When on **OSX**, the speedup ratio is close to the num_threads.

Close this.
