### ISSUE TITLE
Warnings on Visual Studio 2017 x64 (15.9.4)

### ISSUE THREAD

**Issue by bsviglo** [cpp-taskflow/cpp-taskflow#58]
\cpp-taskflow\include\taskflow\threadpool\workstealing_threadpool.hpp(570): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data

**Comment by twhuang-uiuc** [comment]
This is strange. I am looking into it. As far as I know, you can ignore this warning. It doesn't cause any problems.
