### ISSUE TITLE
gcc 7.3.0 with c++17 compile error

### ISSUE THREAD

**Issue by wjx0912** [cpp-taskflow/cpp-taskflow#59]
error screenshot: (the source code only include #<taskflow.hpp>,  cflags is: -std=c++17)
http://98.142.142.53/cpp-taskflow-compile.png

here is my gcc info:
`root@imx8mqevk:~/mnt/source/capture_and_encode# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-poky-linux/7.3.0/lto-wrapper
Target: aarch64-poky-linux
Configured with: ../../../../../../work-shared/gcc-7.3.0-r0/gcc-7.3.0/configure --build=x86_64-linux --host=aarch64-poky-linux --target=aarch64-poky-linux --prefix=/usr --exec_prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/libexec --datadir=/usr/share --sysconfdir=/etc --sharedstatedir=/com --localstatedir=/var --libdir=/usr/lib --includedir=/usr/include --oldincludedir=/usr/include --infodir=/usr/share/info --mandir=/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-libtool-sysroot=/home/chunrong/fsl-arm-yocto-bsp/build-xwaylandimx8/tmp/work/aarch64-poky-linux/gcc/7.3.0-r0/recipe-sysroot --with-gnu-ld --enable-shared --enable-languages=c,c++ --enable-threads=posix --enable-multilib --enable-c99 --enable-long-long --enable-symvers=gnu --enable-libstdcxx-pch --program-prefix=aarch64-poky-linux- --without-local-prefix --enable-lto --enable-libssp --enable-libitm --disable-bootstrap --disable-libmudflap --with-system-zlib --with-linker-hash-style=gnu --enable-linker-build-id --with-ppl=no --with-cloog=no --enable-checking=release --enable-cheaders=c_global --without-isl --with-sysroot=/ --with-build-sysroot=/home/chunrong/fsl-arm-yocto-bsp/build-xwaylandimx8/tmp/work/aarch64-poky-linux/gcc/7.3.0-r0/recipe-sysroot --with-gxx-include-dir=/usr/include/c++/7.3.0 --without-long-double-128 --enable-nls --enable-initfini-array --enable-__cxa_atexit
Thread model: posix
gcc version 7.3.0 (GCC) `

**Comment by twhuang-uiuc** [comment]
Hi @wjx0912 , this is a gcc bug in handling std::optional on a class without copy constructor. I have seen this under some distributions. Would you please try gcc 8 and see if the problem still exists?

**Comment by wjx0912** [comment]
@twhuang-uiuc 
thank your for reply. i use it on arm(imx8, host compile), the rootfs only support gcc7.3.0

**Comment by yrashk** [comment]
Can confirm that this does indeed fail to compile on gcc 7.3.0 and and works on gcc 8.2.0
