### ISSUE TITLE
Subflows in a parallel_for

### ISSUE THREAD

**Issue by igsoft** [cpp-taskflow/cpp-taskflow#60]
I'm experimenting with taskflow and in some cases would be useful to have dynamic subflows inside a parallel_for to continue to generate tasks. Is this possible with the current interface? If yes could you write a small example?

**Comment by clin99** [comment]
Hi @igsoft ,  currently the `parallel_for` API does not support dynamic tasking, but it's very easy to write one from scratch:

```cpp
  tf::Taskflow taskflow;
  std::vector<int> my_data;

  for(size_t i=0; i<my_data.size(); i++) {
    taskflow.silent_emplace([&, i=i](auto &subflow){
       // Increase each element by one
       my_data[i] += 1;

       // Spawn new task using subflow
       subflow.silent_emplace([&, i=i](){
         // Multiply each element by two
         my_data[i] *= 2;
       });
    });
  }
```

Please let me know if this does not fit your needs.

Thanks!

**Comment by igsoft** [comment]
Hi @clin99, I think that a future extension of the parallel_for to support dynamic tasks could be a useful addition to the library.
Anyway, thanks for the quick answer and for the clarifying example!!
