### ISSUE TITLE
thinking about how to integrate into bazel

### ISSUE THREAD

**Issue by luxe** [cpp-taskflow/cpp-taskflow#61]
**Is your feature request related to a problem? Please describe.**
I want to integrate this library into a [bazel](https://bazel.build/) project.  This would require building it from source and then using it in bazel rules.

**Describe the solution you'd like**
A bazel BUILD file that can build and use this project.  
I think I can pull it off by using the foreign rules here:  
https://github.com/bazelbuild/rules_foreign_cc

**Describe alternatives you've considered**
It would probably be better than trying to write a bunch of individual BUILD files and then try to get you to merge and support those.

**Additional context**
I just wanted to make an issue so you knew I was working on it, and if you had any comments yourself.  thanks!

**Comment by luxe** [comment]
oh, is this header only?  why is eign and tbb in here?

**Comment by clin99** [comment]
Hi @luxe ,  `Cpp-Taskflow` is header-only. The Eigen and TBB are only used for benchmarking (under the `benchmark` folder) and won't be built by default (so you don't need to download Eigen or TBB for using `Cpp-Taskflow`). You can simply copy the `taskflow` folder into your project and add this line:  

`#include <taskflow/taskflow.hpp>`  

into your source code. For more details, please refer to the [cookbook](https://cpp-taskflow.github.io/cpp-taskflow/index.html#HowToInstallCppTaskflow) here. 

Thanks.
