### ISSUE TITLE
[Question] example/dynamic_traversal performance

### ISSUE THREAD

**Issue by Nic30** [cpp-taskflow/cpp-taskflow#63]
Hello,

why is the parallel version of dynamic traversal example so much slower? I understand that it is caused by communication overhead between the worker processes. I expect that there is some queue of tasks and that is the limit.

Is it possible to tune-up taskflow for large number of small tasks (for BFS like algorithms)?

Is there any performance comparisons with boost threadpool?

```
$ ./dynamic_traversal seq
Seq runtime: 37
./dynamic_traversal seq tf
Tf runtime: 677

./dynamic_traversal
Tf runtime: 668
./dynamic_traversal tf
Tf runtime: 651

```

**Comment by twhuang-uiuc** [comment]
Hi @Nic30 , this is just an example to demonstrate how to program a graph workload using Taskflow. It may not always be faster than the sequential version depending on the workload you have for each vertex. In this example, each vertex does nothing so sequential version can be faster. Keep in mind parallel execution does have some overhead.

**Comment by Nic30** [comment]
@twhuang-uiuc, I was just curious if it is possible to tweaks the task distribution.

In case of BFS the solution is process multiple vertex per task to minimize communication overhead.
