### ISSUE TITLE
Longer-running tasks with Framework

### ISSUE THREAD

**Issue by ibaned** [cpp-taskflow/cpp-taskflow#67]
Hello! First off, thank you for implementing `Framework`, this is exactly what I would need to use `TaskFlow` in my physics simulation code. In particular, each time step of the simulation is a set of tasks with dependencies between them, and the simulation should continue to execute this task graph in a loop until the time variable reaches a user-specified value.

I had a question about a slightly more complex case that I'd like to do as well:

My simulation spends a long time writing to files, but it doesn't write to a file every single time step. It only writes to a file when the time variable is a multiple of some large number. Is there a way to simultaneously dispatch one task (the file writing task) and a framework `run_until` (the normal simulation time steps), then wait on both of them? That way I could allow the file writing to be concurrent with many time steps, until the next file write is needed.

**Comment by clin99** [comment]
Hi @ibaned , Thank you for the interests in using the library!  Based on my understanding, you can use dynamic tasking to parallelize the simulation tasks and file writing task.  The idea is to create a dynamic task to dispatch the file writing task and this dynamic task precedes simulation tasks.

Below is the code:
```cpp
int user_specified_value;   
int large_number;  
int time_step = 0;    

tf::Taskflow taskflow;
Framework framework;

auto first_task = framework.emplace(
  [&](auto& subflow) {
     if(time_step % large_number) {
       // If time_step is a multiple of the large_number, dispatch a file writing task
       subflow.emplace([]() {
          // write to file
       })
       subflow.detach()   // Detach the subflow so the file writing task will be executed in parallel
     }
     time_step ++;
  }
);

// Add simulation tasks here
// ....

// Make the first_task execute before simulation tasks.  We only need to precede the source tasks here.
first_task.precede(simulation_tasks)

// Run the simulation until reaching a user-specified value
taskflow.run_until(framework, [&](){ return time_step == user_specified_value;});
```
The task dependency graph of the framework will look like this:
  
![taskgraph](https://user-images.githubusercontent.com/34017491/53041794-75cb6900-344a-11e9-8e83-9a6756de8433.png)

Thanks!

**Comment by ibaned** [comment]
Perfect! This looks like it would work, now I will have to try the library :)
The question for this issue is answered, so feel free to close it.
