### ISSUE TITLE
Warning in basic_taskflow.hpp on Visual Studio 2017 x64 (15.8.4)

### ISSUE THREAD

**Issue by Pursche** [cpp-taskflow/cpp-taskflow#71]
When compiling Taskflow in VS2017 we get a warning like this:
Warning	C4267	'argument': conversion from 'size_t' to 'int', possible loss of data
In \taskflow\taskflow\graph\basic_taskflow.hpp on line 478 (this points to the wrong line but whatever)

The actual line that causes this is the following:
node->_num_dependents = node->_dependents.size();
By static casting it like so, we fixed the issue:
node->_num_dependents = static_cast<unsigned int>(node->_dependents.size());

I would like to end this issue by saying that I absolutely love taskflow, and the fact that my first reported issue is something as minor as a warning (which triggers our "treat warnings as error" flag, but still) speaks for itself. Great job so far and thank you! :)

**Comment by clin99** [comment]
Hi @Pursche , thanks for reporting this issue!   I have fixed the warning by adding a `static_cast`.
We are glad this project is useful to you and greatly appreciate your feedback!
Please let us know if you have any questions in the future (or anything you think can improve the library) :)

**Comment by robinchrist** [comment]
@clin99 
Is there any specific reason for using `std::atomic<int>` instead of `std::atomic<unsigned int>`?

**Comment by clin99** [comment]
Hi @robinchrist , currently there is no specific reason for not using `unsigned int`. However according to the [Google style guide](https://google.github.io/styleguide/cppguide.html), unsigned integer is preferred when representing bitfields or modular operation.

Thanks!
