### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by Milerius** [cpp-taskflow/cpp-taskflow#77]
It's can be great if we can make a contact with official bincrafters from conan so they add cpp-taskflow officialy to their remote

**Comment by clin99** [comment]
Hi @Milerius , thanks for the suggestion!  I will contact them to see how to make a Conan package for Cpp-Taskflow.

**Comment by Hopobcn** [comment]
Maybe a cpp-taskflow user could be created in bintray (after all, its free for open source projects) while we wait for bincrafters?

If anyone is interested, i've forked the project and created a conan header-only recipy to try the idea.
More info here https://github.com/Hopobcn/cpp-taskflow/commit/6a4317a9d145ceb52716dce2de86354b0512904e
The package creation & upload to bintray can also be automated with [travis-ci](https://travis-ci.org/Hopobcn/cpp-taskflow) [example](https://bintray.com/hopobcn/public/cpp-taskflow%3Ahopobcn/2.1.0%3Astable#)

**Comment by Hopobcn** [comment]
Already available in conan-center-index:
`conan install cpp-taskflow/2.2.0@`
