### ISSUE TITLE
Readme still up to date?

### ISSUE THREAD

**Issue by KingDuckZ** [cpp-taskflow/cpp-taskflow#81]
I'm referring to this line from the readme:

    auto [A, fu] = tf.emplace([] (tf::SubflowBuilder& subflow) {});

This used to work fine with v2.0 in my project but after updating to master today I get a build error: "cannot decompose inaccessible member tf::Task::_node of tf::Task".

Is it still possible to obtain a future from a subtask? I need that future so I can pass it to task B (A.precede(B);)

**Comment by tsung-wei-huang** [comment]
Hi @KingDuckZ ,  Sorry I just updated the README. The newest version of cpp-taskflow has removed the support for future from creating a task. I know there are some inconvenience but we having this `std::future` return becomes unnecessary for our programming model. It also has limitation in extending our architecture to deal with more complex workload. 

However, considering the shared-memory environment, we believe most of data passing can be worked out without future. For example, you can also capture a variable by reference and build up the dependency between tasks to avoid data race.

**Comment by KingDuckZ** [comment]
I see, thanks for the quick reply! So what happens to the return value of my task now? is it simply discarded?

**Comment by tsung-wei-huang** [comment]
@KingDuckZ  yes, we do not handle anything in your return value.

**Comment by KingDuckZ** [comment]
Thanks, I think I've got my code working fine with the latest version now. Overall I think it's better done this way than with a future indeed.

A minor problem I encountered is that you can't pass a non-copyable lambda to emplace(). It's a shame because you're doing all the perfect forwarding right until you hit a retarded std::function that just wants to copy-construct its callable parameter. I'm not sure if there's an easy fix for this, it's really the C++ committee's responsibility I think, but maybe a workaround could be to type-erase the callable and store it alongside with the std::function just to keep it alive, and then just pass a reference to the std::function. It should work with just a little overhead (1 malloc, some extra class storage, 1 call indirection), but I think there will be lots of adaptation code to type.
