### ISSUE TITLE
Build error using 18.04.2 x64 and g++ 7.4.0

### ISSUE THREAD

**Issue by aogrcs** [cpp-taskflow/cpp-taskflow#86]
Hi
I build the simple.cpp using
g++ simple.cpp -std=c++1z -O2 -lpthread -lstdc++fs -o simple
the error is
simple.cpp:6:10: fatal error: taskflow/taskflow.hpp: No such file or directory
I have already add the path /home/talos/cpp-taskflow which includes taskflow/taskflow.hpp
Could someone help me? Thanks!

**Comment by clin99** [comment]
Hi @aogrcs , could you please go into the cpp-taskflow folder and try following command:
```cpp
g++ -std=c++17 -I . example/simple.cpp -pthread -lstdc++fs
```
If this works, then the problem might be in your path setup.

Thanks.

**Comment by aogrcs** [comment]
Hi @clin99 It did work, so I should check the path setup. Thanks!
I also mkdir build && cd build && cmake .. && make, it worked!
