### ISSUE TITLE
On using cpp-taskflow in  C

### ISSUE THREAD

**Issue by erling-d-andersen** [cpp-taskflow/cpp-taskflow#90]
Here I summarize an offline discussion I have had with Tsung-Wei. He suggested I should do it.

I have been using Intel Cilk to parallelize some code i.e. numerical computations where everything is done in C and NOT C++.  However Cilk is going to be discontinued and Intel suggest to use TBB or OpenMP.  I am not a big fan of OpenMP. And TBB is a C++ code. There simply does not seem to be a good solution for us C programmers.

[You can find a ton of half baked C tasking libraries on Github but none seem to have the quality of cpp-taskflow.]

cpp-taskflow is also C++ but since it is a header only implementation I think I can link it into my code with a static version of the C++ library. That way my DLL/SO will have no explicit c++ dependencies.

Currently, I have defined a simple C interface to cpp-taskflow and tested it versus Cilk (Intel C implementation) . Performance wise there does not seem to a big difference.

The C interface does not have all syntactic sugar and convenience of C++ of course but this simple interface seems good enough for my purpose. There are no secrets in what I am doing but is still playing around, so code is not ready for release.

I am likely to post some questions as I am moving forward.

**Comment by erling-d-andersen** [comment]
I have question about executor. Let us assume I create an executor called E. Then can I use that from any thread?

For instance assume that I am executing a task flow called A then can I execute taskflow say B on a task in A using E.

[In Cilk you can spawn tasks recursively.]

**Comment by tsung-wei-huang** [comment]
Yes. everything in taskflow is object oriented. You can use if from any thread SUBJECT TO one thread access it at a time. The object is not thread-safe.

**Comment by erling-d-andersen** [comment]
My plan does not exclude that the executor could be used from multiple threads at the same time. 

The reason for using 1 executor is to prevent overcomttting just like you do in CIlk.

Have to go back and think then.

**Comment by sampotter** [comment]
@erling-d-andersen Did this go anywhere? I'm also interested in having access to something like Taskflow but from C. Curious to hear what you found... There does not seem to be a good solution currently, unless I am unaware of it. Thanks.

**Comment by erling-d-andersen** [comment]
We decided to use oneTBB.
