### ISSUE TITLE
Question: How does observer mode avoid multi thread writing?

### ISSUE THREAD

**Issue by hongyx11** [cpp-taskflow/cpp-taskflow#91]
I am reading the observer.hpp code, the on_entry and on_exist method.
Does observer.hpp run on multithread env?
If so, there is no lock scheme.

Thanks!

**Comment by tsung-wei-huang** [comment]
Hi, multiple threads can call `on_entry` and `on_exit`. The `ExecutorObserver` handles this by creating a execution timeline data structure per thread at the call of `set_up`

**Comment by hongyx11** [comment]
Okay, I got it! `std::vector<std::vector<Execution>> executions` this guy is a 2-D vector where each entry saves the timeline of one thread. One thread only operates on a certain entry and there is no intervention, right?
Thanks!

**Comment by tsung-wei-huang** [comment]
@hongyx11  yes :)
