### ISSUE TITLE
any plan for c++14 support?

### ISSUE THREAD

**Issue by sumory** [cpp-taskflow/cpp-taskflow#93]
for lots of production systems built with gcc4.9, so it would bring cpp-taskflow more users with c++14 support.

**Comment by tsung-wei-huang** [comment]
@sumory , this is a frequent question and it might be difficult to provide the compatibility with C++14. But, let me discuss with the team to see if this can be in our to-do list.

**Comment by dolphineye** [comment]
Hi :)

I second that request, since in my company, we're stuck to C++14. Our target platforms lack of a (decent) C++17 compiler support. Any news about this? 

Thanks!

**Comment by clin99** [comment]
Hi @dolphineye , I have added this into my TODO list as currently I am working on another issue. I’ll post an update here when it’s done. Thank you for your patience!

**Comment by dolphineye** [comment]
@clin99 No problem. This can wait. Thanks for your quick reply!

**Comment by sumory** [comment]
@clin99 hi, is there any progress for this feature up to now?

**Comment by clin99** [comment]
Hi @sumory , I have implemented a C++14 version, but currently the code hasn't been tested and it needs to be refactored. I will try to get these done as soon as I have free time.

Thank you for your patience.

**Comment by facontidavide** [comment]
Looking forward for this.

**Comment by clin99** [comment]
Hi all, we have created a Cpp-Taskflow branch with C++14 support. Please find the source code [here](https://github.com/cpp-taskflow/cpp-taskflow/tree/cpp14). The minimum compiler version we have tested are GCC 5.3 and Clang 5.0. Let us know if you have any question.

Thanks.

**Comment by sumory** [comment]
not work at GCC 4.9.2 which is our production environment. :(

**Comment by clin99** [comment]
Hi @sumory , please download the [cpp14 branch](https://github.com/cpp-taskflow/cpp-taskflow/tree/cpp14) and replace the following three files:

[executor.txt](https://github.com/cpp-taskflow/cpp-taskflow/files/3899205/executor.txt): use this file to overwrite the `executor.hpp` file under `cpp-taskflow/taskflow/core` (**remember to change the .txt to .hpp**)

[traits.txt](https://github.com/cpp-taskflow/cpp-taskflow/files/3899206/traits.txt): use this file to overwrite the `traits.hpp` file under `cpp-taskflow/taskflow/utility` (**remember to change the .txt to .hpp**)

[CMakeLists.txt](https://github.com/cpp-taskflow/cpp-taskflow/files/3899215/CMakeLists.txt): use this file to overwrite the `CMakeLists.txt` file under `cpp-taskflow/`

This should work under GCC-4.9.4 which is the minimum GCC version we have on our machine. Let us know if this doesn't work with your compiler.

Thanks.

**Comment by sumory** [comment]
@clin99 it works!

**Comment by tsung-wei-huang** [comment]
@sumory  The master branch now is fully C++ compliant. Please try!
