### ISSUE TITLE
Usable on system with no threads?

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [cpp-taskflow/cpp-taskflow#94]
Not really a feature request but a question. (or a request if it isn't supported)
It is possible to use this library on platform with no thread support, ie: web/emscripten and older mobiles. Such that the same code written for desktop with this library run on those platform but sequentially, in the main thread?

**Comment by clin99** [comment]
Hi @UNDEFINED-BEHAVIOR , This is doable in Cpp-Taskflow. You can specify the number of worker (threads) when creating an `executor`. If the number of worker is 0, the executor will not spawn threads and all tasks will be executed by the main thread. Here is the code:

```cpp
tf::Executor executor(0);   // Create an executor without any worker
```

**Comment by UNDEFINED-BEHAVIOR** [comment]
Hi, finally got to try it out for real and the simple example works.

**Comment by clin99** [comment]
Hi @UNDEFINED-BEHAVIOR , glad it works!  Please let us know if you see other issues or anything we can improve.

Thanks.
